### ISSUE TITLE
Fabric crafting recipes don't work

### ISSUE THREAD

**Issue by SageofTurtles** [MisterJulsen/Create-Train-Navigator#13]
**Version:**
 - Minecraft Version: 1.20.1
 - FABRIC Version: 0.15.7
 - Mod Version 0.5.1-beta-1.20.1 (Fabric)

**Describe the bug**
The crafting recipes for the navigator, train station clock, advanced display, and advanced display block do not work in the new Fabric version of the mod.  Looking at the recipe files, these appear to use Forge item tags in the crafting recipes, which I assume is why they don't work in Fabric.

**To Reproduce**
1. Install the Fabric mod version (I am using 0.5.1 for 1.20.1 Fabric, but this could affect the other Fabric mod versions as well)
2. Open a new world
3. Attempt to craft any of the above-listed items, which will fail.

**Comment by MisterJulsen** [comment]
Should be fixed in the latest update beta-0.5.2
