### ISSUE TITLE
Changing a display to double-sided also affects adjacent screens even if they are not aligned

### ISSUE THREAD

**Issue by slmnio** [MisterJulsen/Create-Train-Navigator#15]
**Version:**
 - Minecraft Version: 1.20.1
 - fabric-api 0.91.0+1.20.1
 - fabricloader 0.15.7
 - Mod Version 0.5.2-beta-1.20.1

**Describe the bug**
When toggling the double sided function of a display, it will also affect any display that is adjacent to it, including displays that are adjacent but aligned differently (e.g. different Z alignments)

**To Reproduce**

[java_SbEfa1NhFs.webm](https://github.com/MisterJulsen/Create-Train-Navigator/assets/15251071/259240e1-e88f-4d44-ba70-7e1de1c3a70b)

**Expected behavior**
Changing the double sided checkbox should not affect displays that are not actually part of the connected display.

**Comment by MisterJulsen** [comment]
Thanks for your report! Should be fixed in the latest update beta-0.5.3 👍🏼
