### ISSUE TITLE
Crash when updateing from 0.5.3 to 0.5.4 on start up

### ISSUE THREAD

**Issue by bangetto** [MisterJulsen/Create-Train-Navigator#27]
**Version:**
 - Minecraft Version: 1.20.1
 - Fabric: 0.15.11
 - Mod Version 0.5.4

**Describe the bug**
The game crashes on startup when I updated the mod to 0.5.4, switching back to 0.5.3 and it started up

**To Reproduce**
1. install modpack: https://modrinth.com/modpack/create-d/version/3z9OGh6Q
2. update CRN
3. observe crash

**Expected behavior**
the game should start up

**Screenshots**

**Additional context**

**Comment by MisterJulsen** [comment]
Do you have a crash log? That would help a lot

**Comment by bangetto** [comment]
[crash-2024-06-27_20.03.47-client.txt](https://github.com/user-attachments/files/16030365/crash-2024-06-27_20.03.47-client.txt)

**Comment by bangetto** [comment]
the update solved it
