### ISSUE TITLE
Advanced Displays don't show the trains and stopping stations successfully.

### ISSUE THREAD

**Issue by AIR-1-9-18** [MisterJulsen/Create-Train-Navigator#30]
**Version:**
 - Minecraft Version: 1.19.2
 - Forge Version 43.4.0
 - Mod Version 0.5.4-beta-1.19.2

**Describe the bug**
Passenger Information mode does not show train's all stop station, instead it shows not all of them but only the next station after the train departs the previous station.
Also, in platform display mode, only trains that have departed from the previous station are shown on the display for the next station, and not on other displays where trains are expected to stop, nor on the next diagram.

**To Reproduce**
1. Create a train and its schedules
2. Place an Advanced Display in a train or a platform
3. Things described above will happen

**Expected behavior**
Successfully show all schedules for trains and platforms.

**Additional context**
It only caused when I make the schedule that use like "move to station ABC (departure at hh:mm a.m./p.m.)"

**Comment by MisterJulsen** [comment]
should be fixed in beta-0.6.0
