### ISSUE TITLE
How does one threaten a station?

### ISSUE THREAD

**Issue by DadamaldaDad** [MisterJulsen/Create-Train-Navigator#43]
**Version:**
 - Minecraft Version: 1.20.1
 - Forge Version 47.1.43
 - Mod Version 1.20.1-0.5.5

**Describe the bug**
There is a typo that says "threaten" instead of "treat" in the text in the screenshot.

**To Reproduce**
1. Open the navigator
2. Open global settings
3. Look at the text below "Train Station Tags"

**Expected behavior**
The text should say "treat"

**Screenshots**
![Snímek obrazovky 2024-08-21 090953](https://github.com/user-attachments/assets/ff4ba17d-4d5a-49a5-afdd-3d9e073be93d)

**Additional context**
It seems very rude to threaten a train station, especially when it's multi-platform.

**Comment by MisterJulsen** [comment]
fixed in beta-0.6.0
