### ISSUE TITLE
Critical Performance Problem

### ISSUE THREAD

**Issue by MegumiKasuga** [MisterJulsen/Create-Train-Navigator#46]
**Version:**
 - Minecraft Version: 1.19.2
 - Forge Version 43.3.7
 - Mod Version 0.5.4

**Describe the bug**
    A critical performence problem that caused the server stuck. (low tps(10) and bad gaming experience)
    Follow methods may be the cause of this problem.
    ![Image_1727611700822.png](https://github.com/user-attachments/assets/dd0b4d40-4d5e-4566-87ec-1d68b72b0613)

**To Reproduce**
    1. Navigators in forced load chunks.
    2. Large scale (complicated) train networks.

**Expected behavior**
    Server tps got low. (10tps/100mspt)

**Screenshots**
    Monitor: 
    ![Image_1727612296222.png](https://github.com/user-attachments/assets/a3d95bff-e54f-4874-867b-bf8c8d2875b4)

**Additional context**
    Maybe a cache(like LazyRecomputable) would be a good solution for this problem. Stop your algorithm from scaning create's data structure all the time.
    Wish you a good day.

**Comment by MisterJulsen** [comment]
The performance should be much better in beta-0.6.0
