### ISSUE TITLE
Next stop and "via" not displaying correctly

### ISSUE THREAD

**Issue by venusitaa** [MisterJulsen/Create-Train-Navigator#47]
- Minecraft Version: 1.20.1
 - Forge Version 47.3.0
 - Mod Version 0.5.5

When connecting multiple stations in a loop, the next stop and via texts display wrong info. 
Ex: when having S1, S2, S3 and S4 looped, going from S1 to S2 will display as soon as leaving the station as S3 via S3 + S4 which makes no sense.

**To Reproduce**
1. Create looped rail system
2. Place advanced board or display inside train
3. Watch displayed data

**Expected behavior**
When going from S1 to S2, display Next stop as S2 via S1, then S3 via S2 etc

**Comment by MisterJulsen** [comment]
in beta-0.6.0 it is possible to select the terminus and some other things. I hope this helps
