### ISSUE TITLE
Advanced display and schedule board improvement

### ISSUE THREAD

**Issue by skybird-r** [MisterJulsen/Create-Train-Navigator#53]
**Is your feature request related to a problem? Please describe.**
- When using the schedule section as shown below, it is unhelpful that the advanced display at Station A only shows 'from X' until the train arrives, without displaying the destination C.

    (new schedule section) → X → Y → (new schedule section) → A → B → C

**Describe the solution you'd like**
- Display the destination and schedule title even while the train is on the way.

In relation to this, I propose adding a mode to the schedule board that displays only departures, rather than arrivals.

**Comment by jiugulixiaoniu** [comment]
我什么都不显示………………

**Comment by MisterJulsen** [comment]
This can be changed in the latest version
