### ISSUE TITLE
breaking apotheosis recipes

### ISSUE THREAD

**Issue by MisteryDuck** [MisterJulsen/Create-Train-Navigator#56]
**version:**
 - Minecraft Version: 1.19.2
 - Forge Version 43.3.8
 - Mod Version: forge-1.19.2-0.6.0
 
after updating the mod from the previous version to the latest it started to break some apotheosis recipes. Mainly all of the gem socketing recipes, tomes and some bookshelves. I'm not sure what could be causing the problem, but I've confirmed that it only happens with this mod.

### to reproduce:
* install apotheosis and it's dependencies
* install create and create railways navigator
* create a world
* check gem socketing recipes

small modpack with the mods installed and a test world: [1.19.2.zip](https://github.com/user-attachments/files/17641376/1.19.2.zip)

![image](https://github.com/user-attachments/assets/8a1731bd-3d1c-4185-8d23-5e48e9d88bcb)

**Comment by MisterJulsen** [comment]
Should be fixed in the latest version
