### ISSUE TITLE
Route overlay showing different times (6 hours shifted)

### ISSUE THREAD

**Issue by Quatryl23** [MisterJulsen/Create-Train-Navigator#58]
**Version:**
 - Minecraft Version: [1.20.1]
 - Forge Version [47.3.0]
 - Mod Version [0.6.0]

**Describe the bug**
The times shown in the route overlay are two different ones. In my example shown below, the times are 22:07 and 04:07, while 04:07 is the correct one. This occured multiple times - Every time the wrong time was the correct one but shifted by 6 hours. I don´t think that´s intended. Everything else is showing the correct times, only the route overlay´s orange text shows a different one.

**To Reproduce**
1. Construct a train network with at least one passenger train with train schedule.
2. Try to use the route overlay to show a depature time.
3. It´s probably not the correct time shown in the orange text line.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/0f57ae6a-0eff-4431-ad18-c9fce77419a5)

**Additional context**
I´m using Create: Steam n rails but nothing else that should interact with trains in any way.

**Comment by MisterJulsen** [comment]
Should be fixed in the latest version
