### ISSUE TITLE
Server keep updating "Save global setting" frequently

### ISSUE THREAD

**Issue by OstiumAxioma** [MisterJulsen/Create-Train-Navigator#63]
**Version:**
 - Minecraft Version: [1.20.1]
 - Forge Version [47.3.7]
 - Mod Version [0.6.0]

**Describe the bug**
On server side it keeps generating logs with message:

Save global setting

**To Reproduce**
1. Launch the server
2. Create any train
3. Run the train
4. Start using navigator once

**Expected behavior**
Nothing on client side, but server side will start generating "Save global setting" on a frequency of one logs per 3 seconds.

**Screenshots**

**Additional context**

**Comment by MisterJulsen** [comment]
The bug has been reported several times and will be fixed in the next update, which is coming soon

**Comment by MisterJulsen** [comment]
Should be fixed in the latest version
